### ISSUE TITLE
Trimming or customizing word lists

### ISSUE THREAD

**Issue by Poobslag** [cynicaloptimist/longwave#2]
While playing, we occasionally see some spectrum cards which are synonyms or gibberish. I've played the physical Wavelength board game 5-10 times but never seen any spectrums like these. Frankly, we just don't have much fun when they show up online.

`Tick ... Tock`

The dictionary defines these as 'sound made by a clock'. Am I missing something? What's the intended spectrum? What's a good clue that would be, say, 75% Tock? "Tooioooiock"?

`Weird ... Strange`

These are both synonymous with 'unusual', 'foreign', 'alien'. Is a UFO "weird" or "strange"? Is a haunted house "weird" or "strange"? The dictionary defines weird as "suggesting something supernatural; uncanny" so presumably a haunted house should be on the 'weird' side but I can't imagine anybody would find this spectrum intriguing or fun.

`Illegal ... Prohibited`, `Small ... Tiny`, `Etiquette ... Manners`

More of the same. Is littering "Illegal" or "Prohibited"? Is a thimble "Small" or "Tiny"? Is sitting up straight "Etiquette" or "Manners"? They're all both. Maybe a group could decide collectively, "For this card 'etiquette' is going to mean things that you might do around your friends but not to your boss, but 'manners' is going to mean things that you wouldn't do around anybody at all," and then the cards might be fun. But I feel like any fun discussions for these spectrums would center around how bizarre the card is, and how we can fix the card so that it actually works.

Is it possible to trim the spectrum cards to only include things that are different? Or perhaps to let us paste in a giant `.txt` or `.ts` file defining our own spectrum cards, so that we can edit out the ones we don't find fun? In the meantime we've just house ruled to make up our own spectrum if the provided spectrum is nonsensical or provides two synonyms.

**Comment by cynicaloptimist** [comment]
All the spectrums in Longwave are ones from the original Wavelength box.
The Wavelength box contains two sets of cards, the "standard" ones and the
"advanced" ones. Some of these advanced ones that you've noticed require
some creative interpretation! Tick ... Tock is a particularly tough one; I
once pulled it and used "Grandfather clock" to indicate somewhere closer to
the "Tock" sound of the spectrum (since it's a bigger clock, you'd think of
it making a deeper sound". A big part of the fun of this game is hoping
your friends interpret the spectrum the same way you do! Some of
the spectrums contain two words that are nearly synonymous, so the
challenge is in figuring out what clue could really demonstrate the nuance
between two nearly-synonymous words. Consider taking another read through
the rule book.

Anyways, if you really hate a card that you've drawn, there's a big button
labelled "Draw a different card".

[image: PXL_20201204_211857979.jpg]

--
Evan Bailey <http://www.linkedin.com/in/evangbailey>

**Comment by Poobslag** [comment]
My mistake -- if those are all from the original game then I can't fault you from including them!

The "Draw a different card" option is unavailable in some modes, such as in the cooperative mode. Otherwise yeah, we just drew a different card.

Thanks so much for developing the app!

**Comment by cynicaloptimist** [comment]
Right on, good point about disabling it in co-op mode, which was intentional. I might add a toggle to turn the advanced cards on/off but this isn't my main project right now. Thanks!
